name: Build RabbitMQ MQTT Cluster Docker Image

env:
    REGISTRY: docker.io
    IMAGE_NAME: ${{ github.event.repository.name }}

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
    image-build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4

            
            - name: Log into registry
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v2
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ secrets.DOCKER_HUB_USER }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                context: .
                push: ${{ github.event_name != 'pull_request' }}
                tags: |
                    davincievans/${{ env.IMAGE_NAME }}:${{ github.sha }}
                    davincievans/${{ env.IMAGE_NAME }}:latest